<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class m_dashboard extends CI_Model {

	public function getRekap($lv,$uk,$dv,$nip){
		if($lv == '0'){
			$query = $this->db->query("SELECT KT.NAMA_UNIT_KERJA AS NAMA_UNIT, COUNT(NILAI_ALKET) AS JUMLAH_DATA_ALKET, IFNULL(SUM(NILAI_ALKET),0) AS JUMLAH_NILAI_ALKET, COUNT(NILAI_REALISASI) AS JUMLAH_DATA_REALISASI, IFNULL(SUM(NILAI_REALISASI),0) AS JUMLAH_NILAI_REALISASI
				FROM alket A RIGHT JOIN unit_kerja KT ON a.UNIT_KERJA_TUJUAN = KT.KODE_UNIT_KERJA
				WHERE KT.KODE_UNIT_KERJA NOT IN ('200')
				GROUP BY KT.NAMA_UNIT_KERJA");
		} else if ($lv == '1'){
			$query = $this->db->query("SELECT NAMA_DIVISI AS NAMA_UNIT, COUNT(NILAI_ALKET) AS JUMLAH_DATA_ALKET, IFNULL(SUM(NILAI_ALKET),0) AS JUMLAH_NILAI_ALKET, COUNT(NILAI_REALISASI) AS JUMLAH_DATA_REALISASI, IFNULL(SUM(NILAI_REALISASI),0) AS JUMLAH_NILAI_REALISASI
				FROM DIVISI D JOIN JABATAN J ON J.KODE_DIVISI = D.KODE_DIVISI
				JOIN JABATAN JB ON JB.JABATAN_INDUK = J.KODE_JABATAN
				JOIN PEGAWAI P ON P.KODE_JABATAN = J.KODE_JABATAN
				JOIN UNIT_KERJA U ON U.KODE_UNIT_KERJA = P.KODE_UNIT_KERJA
				LEFT JOIN DISPOSISI S ON S.PENERIMA_DISPOSISI = P.NIP
				LEFT JOIN ALKET A ON A.NO_ALKET = S.NO_ALKET
				WHERE NAMA_UNIT_KERJA LIKE '%$uk%'
				GROUP BY NAMA_DIVISI");
		} else if ($lv == '2') {
			$query = $this->db->query("SELECT NAMA_PEGAWAI AS NAMA_UNIT, COUNT(NILAI_ALKET) AS JUMLAH_DATA_ALKET, IFNULL(SUM(NILAI_ALKET),0) AS JUMLAH_NILAI_ALKET, COUNT(NILAI_REALISASI) AS JUMLAH_DATA_REALISASI, IFNULL(SUM(NILAI_REALISASI),0) AS JUMLAH_NILAI_REALISASI
				FROM DIVISI D JOIN JABATAN J ON J.KODE_DIVISI = D.KODE_DIVISI
				JOIN PEGAWAI P ON P.KODE_JABATAN = J.KODE_JABATAN
				JOIN UNIT_KERJA U ON U.KODE_UNIT_KERJA = P.KODE_UNIT_KERJA
                LEFT JOIN DISPOSISI S ON S.PENERIMA_DISPOSISI = P.NIP
                LEFT JOIN ALKET A ON A.NO_ALKET = S.NO_ALKET
                WHERE NAMA_UNIT_KERJA LIKE '%$uk%' and NAMA_DIVISI LIKE '%$dv%' and P.NIP != '$nip'
                GROUP BY NAMA_PEGAWAI");
		} else if($lv == '3'){
			$query = $this->db->query("SELECT NAMA_PEGAWAI AS NAMA_UNIT, COUNT(NILAI_ALKET) AS JUMLAH_DATA_ALKET, IFNULL(SUM(NILAI_ALKET),0) AS JUMLAH_NILAI_ALKET, COUNT(NILAI_REALISASI) AS JUMLAH_DATA_REALISASI, IFNULL(SUM(NILAI_REALISASI),0) AS JUMLAH_NILAI_REALISASI
				FROM DIVISI D JOIN JABATAN J ON J.KODE_DIVISI = D.KODE_DIVISI
				JOIN PEGAWAI P ON P.KODE_JABATAN = J.KODE_JABATAN
				JOIN UNIT_KERJA U ON U.KODE_UNIT_KERJA = P.KODE_UNIT_KERJA
                LEFT JOIN DISPOSISI S ON S.PENERIMA_DISPOSISI = P.NIP
                LEFT JOIN ALKET A ON A.NO_ALKET = S.NO_ALKET
                WHERE NAMA_UNIT_KERJA LIKE '%$uk%' and NAMA_DIVISI LIKE '%$dv%' and P.NIP = '$nip'
                GROUP BY NAMA_PEGAWAI ");
		}

	return $query;
	}
}

/* End of file m_dashboard.php */
/* Location: ./application/models/m_dashboard.php */